# render.yaml
services:
  - type: web
    name: speaking-coach-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    autoDeploy: true
